/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

int main(void)
{

	RCC_AHB1ENR_t *pClkRegENR = (RCC_AHB1ENR_t*)0x40023830;

//	uint32_t* pClkRegENR = (uint32_t*)0x40023830;

	GPIOx_MODER_t *pGPIOBmodeReg = (GPIOx_MODER_t*)0x40020400;

//	uint32_t* pGPIOBmodeReg = (uint32_t*)0x40020400;

	GPIOx_ODR_t *pGPIOBoutReg = (GPIOx_ODR_t*)0x40020414;

//	uint32_t* pGPIOBoutReg = (uint32_t*)0x40020414;

    // GPIOB CLK
	pClkRegENR -> gpio_enb = 1;

	//a. clear the 14th and 15th bit positions (CLEAR)
	pGPIOBmodeReg -> pin_7 = 1;

//	//b. make 14th bit position as 1 (SET)
//	*pGPIOBmodeReg |= 0x00004000;

	//turn on the LED
	pGPIOBoutReg -> pin_7 = 1;





    /* Loop forever */
	for(;;);
}

